### ISSUE TITLE
Sprint 2 - Build/Test/Revise

### ISSUE THREAD

**Issue by mrfabroa** [sta-titansrobotics/27316-IntoTheDeep#11]

**Comment by fistik12** [comment]
![20241017_152428.jpg](https://github.com/user-attachments/assets/7bca8489-e872-4a1a-8492-12e3a3c5f4df)

After school today, I managed to start attaching the arm to the drivetrain with the available time designated.

Success
-started attaching the arm to the drivetrian
Utilizing parts in the FTC starter bundle

Failure
- Unfortunately, I didn't have enough time to properly fasign the arm to the drivetrain, hope to complete it tomorrow

By the end of the week, we hope to complete the attachment of the arm to the drivetrian.

**Comment by athishasurees** [comment]
Me and Michelle want to finish the forearm/claw in the first few days of this sprint, because we are nearly done but we need to finish a few more things and tighten a bunch of things to make everything secure. After this, we want to help our group with putting all the parts together. After completing this, our group wants to ensure that the height of the robot is able to reach the top bin, and may need to adjust some parts.

**Comment by athishasurees** [comment]
Me and Michelle spent the first 3 days working on finishing our forearm/claw, because we wanted to put all the parts together. We were very proud of ourselves. We made a lot of mistakes and most of our days were spent on trying to perfect the mistakes that we already made and were trying to fix, or we didn't understand what the instructions wanted us to do. 

![pic 5](https://github.com/user-attachments/assets/bd3429c2-3ef3-490a-a333-02b24ed96c71)
![pic 6](https://github.com/user-attachments/assets/e46f5519-0aa1-496a-a64c-4a146fd3920a)

**Comment by athishasurees** [comment]
Oct 19 - P. A Day, no school.

**Comment by athishasurees** [comment]
Oct. 20th - We all completed our individual parts and we decided to fasten everything together. The first problem we ran into was that some of the parts didn't fit with each other. for example, the intake assembly didn't match the forearm/claw. the extrusion on the intake was too big for the extrusions on the forearm/claw.

**Comment by athishasurees** [comment]
October 23rd - We spent the day making changes to all of the parts, and then we put all the parts together. We put it on the field to see if the arm would even reach the bins, and we figured it out that it didn't. The group decided that we had to redo some parts to adjust to the height of the basket. Essentially, the intake should be reaching the basket, but the extrusions were too small, so my group had to redo the whole intake assembly and switch out the extrusions for longer ones so it could reach the basket.

**Comment by athishasurees** [comment]
October 24 & 25th - We were all still working to make adjustments to the robot to make everything fit accordingly. We also attached the control hub onto the robot and trying to find a way to fasten it without everything looking too janky.
