### ISSUE TITLE
Sprint 4: Pass Robot Inspection

### ISSUE THREAD

**Issue by mrfabroa** [sta-titansrobotics/27316-IntoTheDeep#19]
Robot passes [all points of inspection ](https://www.firstinspires.org/sites/default/files/uploads/resource_library/ftc/inspection-checklist.pdf) (Nov 18)

Define and assign the distribution of duties here and create the necessary sub issues. Be sure to set the necessary assignees and label (Inspection) on related issues.

**Comment by fistik12** [comment]
https://www.firstinspires.org/sites/default/files/uploads/resource_library/ftc/inspection-checklist.pdf

Using the official inspection documents by FTC, I will document my progress in accessing the robot and see if the credentials listed on the document pass or fail on our team's robot.

I will be creating separate comments for each section of the document (size, signs, mechanical, electrical, and others such as operator consol rules and software rules.

**Comment by fistik12** [comment]
![20241107_125256.jpg](https://github.com/user-attachments/assets/eccb01e9-25ce-4068-90f3-0d02943c9beb)

**Comment by fistik12** [comment]
<img width="747" alt="Screenshot 2024-11-10 at 6 21 11 PM" src="https://github.com/user-attachments/assets/abf90365-a0e2-4df0-866d-cf36c26be80b">
<img width="747" alt="Screenshot 2024-11-10 at 6 21 49 PM" src="https://github.com/user-attachments/assets/1966ec76-8580-46ed-8335-e003e626325f">

Today (**Nov 10**), I began designing the signage for our team robot. I designed our team number **27316** in red and blue alliance-specific colours, using the dimensions from the official FTC manual. (I designed the signage to be **7x3 inches**)

I believe that the signage should be mounted on the sides since the manual mandates that it be visible from a 12-meter perspective.

In tomorrow's class, I plan to continue the robot's inspection process and begin the mechanical category overview.

**Comment by fistik12** [comment]
![20241111_112325.jpg](https://github.com/user-attachments/assets/28cccbda-823c-4d02-823e-bf5adb512b82)

![20241111_112108.jpg](https://github.com/user-attachments/assets/ad565d64-3a7b-49d8-ba03-208ed0d7433b)

![20241111_112102.jpg](https://github.com/user-attachments/assets/f53e088b-0828-4f23-bce2-202bd27e270f)

![20241111_112537.jpg](https://github.com/user-attachments/assets/efd8edcb-04b5-4e82-af8f-38fe44ad50eb)

Today (Nov 11),

**Comment by fistik12** [comment]
<img width="890" alt="Screenshot 2024-11-11 at 6 00 01 PM" src="https://github.com/user-attachments/assets/fea5a9e5-6e0f-4307-9e22-ab666867243a">

While viewing the manual, the power switch on our robot is required to have the label attached printed near the switch, indicating it is a power switch
