### ISSUE TITLE
Arm: Intake System (from sub)

### ISSUE THREAD

**Issue by PotatoesMashed** [sta-titansrobotics/27316-IntoTheDeep#8]
Here  you will document your progress researching intake and output systems. Should be focused around samples, not speciments.

**Comment by athishasurees** [comment]
1) Objectives 

- Find out how the arm could acquire samples from the arm 
- Research a design that could support this 
- Find issues within the arm intake system and make solution on how to fix them 

Issues: 

- Mechanical Jams 
- Insufficient grip on the items 
-Alignment Problems 


Solutions for each Issue: 

1. Mechanical Jams 

- We can regularly check the arm for debris and ensure that all the moving parts are correctly aligned and nothing is being put into the robot with brute force 
- We could also resign the intake mechanism, and do a design that debris cannot accumulate in important areas, such as wider opening or smoother surfaces 
- We could test out different materials on the robot and intake surface to find things that reduce any jamming or anything that manually causes the robot not to run 

2. Weak Grip on Items 

- Adjust the arm strength to make it flexible to anything that is being gripped 
- We can use different materials for the grippers to enhance any friction and allows the item to be carried throughout the field 
- Some of these materials could be tested with rubber, as that is a reliable source and could attach to virtually anything 
- Adjust the flexibility of the claw (whatever is being used to pick up) so that the arm does not have to be weighted down (put more pressure on the claw and not the arm if the arm is unable to grip/lift the items)

3. Alignment Problems
- Misalignment on the robot and the parts can affect how the arm moves because it might be condensed and the movement may be restricted 
- We could also use adjustable brackets to allow room and fine-tuning the position of the intake components after the initial assembly 
- We could also use visual markers to ensure that we are putting the parts in the correct places 


Designs that could adhere to these issues: 
![image](https://github.com/user-attachments/assets/0211f18c-eed7-4f79-81a7-072b6f65cdfa)
<img width="272" alt="image" src="https://github.com/user-attachments/assets/e30822fa-d1b0-4a2e-8b0f-d2a4b39ca2ce">
https://www.youtube.com/watch?v=vnNqqSb7NYw
